### ISSUE TITLE
Can't remove database record

### ISSUE THREAD

**Issue by JeroenMathon** [JeroenMathon/Bol.com-Demo#18]
I think the main problem might be that the GUI keeps opening a database connection,
SQLite having the disadvantage of being a single file database, is that there can be only one active session in the database.

Stack trace
```
java.sql.SQLException: database is locked
	at org.sqlite.core.DB.throwex(DB.java:859)
	at org.sqlite.core.DB.exec(DB.java:142)
	at org.sqlite.jdbc3.JDBC3Connection.commit(JDBC3Connection.java:165)
	at bolDemo.database.jeroenmathon.dbMgr.removeRecord(dbMgr.java:339)
	at bolDemo.gui.jeroenmathon.staffBrowsePanel.removeRecord(browsePanel.java:143)
	at bolDemo.gui.jeroenmathon.browsePanel.actionPerformed(browsePanel.java:85)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.GNOME.Accessibility.AtkWrapper$5.dispatchEvent(AtkWrapper.java:697)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by JeroenMathon** [comment]
After some testing i can confirm the problem lays within the Graphical User Interface opening the database continuously, Therefore the appropriate solution would be to make the GUI store data on initialization. Then call data again when a refresh is needed(This can be after data has been modified).

**Comment by JeroenMathon** [comment]
Switching to a MYSQL database might be a more viable and realistic solution to this problem.
Allowing multiple connections and it being a more powerful DBMS.
I'm going to run this experiment on a separate branch.

**Comment by JeroenMathon** [comment]
Fixes as i moved the database towards a MySQL database
